resilience4j:
  circuitbreaker:
    configs:
      defecto:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
    instances:
      country-info:
        base-config: defecto
  timelimiter:
    instances:
      country-info:
        timeout-duration: 5s
        cancel-running-future: true